[project]
name = "cuttle"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "apscheduler>=3.11.0",
    "fastapi>=0.116.1",
    "sqlmodel>=0.0.24",
    "transitions>=0.9.3",
    "uvicorn>=0.35.0",
]
